name: Build latest (N64)
on: [push]

concurrency:
  group: ${{ github.ref }}-n64
  cancel-in-progress: true

jobs:
  build:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dragonminded/libdragon:latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile N64 build
        id: compile
        run: |
          REAL_DIR=`pwd`
          cd /tmp
          git clone -b opengl https://github.com/DragonMinded/libdragon.git --depth=1
          cd libdragon
          make install
          make tools-install
          cd $REAL_DIR
          make n64


      # otherwise notify_failure doesn't work
      - name: Install curl when necessary
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        run: apt install curl

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile N64 build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube-n64.z64'
          DEST_NAME: 'ClassiCube-n64.z64'
