name: Build latest (NetBSD)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-netbsd
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cross-rs/x86_64-unknown-netbsd:edge
    steps:
      - uses: actions/checkout@v3
      - name: Install prerequisites
        run: |
          apt-get update
          apt-get -y install zip wget

      - name: Retrieve OpenGL and X11 dev files (64 bit)
        run: |
          mkdir netbsd64
          cd netbsd64
          wget https://github.com/ClassiCube/rpi-compiling-stuff/raw/main/netbsd64.zip
          unzip netbsd64.zip

      - name: Compile NetBSD builds
        shell: bash
        env: 
          LIBS: "-lm -lpthread -lX11 -lXi -lGL -lexecinfo"
          SRCS: "src/*.c third_party/bearssl/*.c"
          FLAGS: "-O1 -s -fno-stack-protector -fno-math-errno -Qn -Werror -Wl,-R/usr/X11R7/lib -fvisibility=hidden -rdynamic -Werror"
          PLAT64_FLAGS: "-fno-pie -fcf-protection=none -I netbsd64/include -L netbsd64/lib -Wl,--unresolved-symbols=ignore-in-shared-libs"
        run: |
          LATEST_FLAG=-DCC_COMMIT_SHA=\"${GITHUB_SHA::9}\"

          x86_64-unknown-netbsd-gcc ${{ env.SRCS }} ${{ env.FLAGS }} ${{ env.PLAT64_FLAGS }} $LATEST_FLAG -o cc-netbsd64-gl1 ${{ env.LIBS }}
          
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'cc-netbsd64-gl1'
          DEST_NAME: 'ClassiCube-NetBSD-64'
          
          
      - uses: ./.github/actions/notify_success
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'netbsd'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce NetBSD build(s)'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
