name: Build latest (N64)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-n64
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dragonminded/libdragon:preview
    steps:
      - uses: actions/checkout@v4
      - name: Compile N64 build
        id: compile
        run: |
          apt-get update
          apt-get -y install curl
          REAL_DIR=`pwd`
          cd /tmp
          git clone -b opengl https://github.com/DragonMinded/libdragon.git --depth=1
          cd libdragon
          make install
          make tools-install
          cd $REAL_DIR
          make n64


      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile N64 build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'build-n64/ClassiCube-n64.elf'
          DEST_NAME: 'ClassiCube-n64.elf'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube-n64.z64'
          DEST_NAME: 'ClassiCube-n64.z64'
          
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'n64'
