name: Build latest (Xbox)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-xbox
  cancel-in-progress: true

jobs:
  build-Xbox:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xboxdev/nxdk:git-e955705a
    steps:
      - uses: actions/checkout@v4
      - name: Compile Xbox build
        id: compile
        run: |
          apk add curl curl-dev
          eval $(/usr/src/nxdk/bin/activate -s)
          make xbox
          cp bin/default.xbe ClassiCube-xbox.xbe
          

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile Xbox build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube-xbox.xbe'
          DEST_NAME: 'ClassiCube-xbox.xbe'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube-xbox.iso'
          DEST_NAME: 'ClassiCube-xbox.iso'
          
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'xbox'