name: Build latest (Saturn)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-saturn
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: ijacquez/yaul:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          apt-get --allow-releaseinfo-change update
          apt-get install -y curl

      - name: Compile Saturn build
        run: |
          make saturn
          
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'build/saturn/ClassiCube-saturn.elf'
          DEST_NAME: 'ClassiCube-saturn.elf'
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube-saturn.iso'
          DEST_NAME: 'ClassiCube-saturn.iso'
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube-saturn.cue'
          DEST_NAME: 'ClassiCube-saturn.cue'
          
          
      - uses: ./.github/actions/notify_success
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'saturn'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce Saturn build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
