name: Build latest (WiiU)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-wiiu
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Wii U build
        run: |
          make wiiu
          
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube-wiiu.wuhb'
          DEST_NAME: 'ClassiCube-wiiu.wuhb'
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube-wiiu.rpx'
          DEST_NAME: 'ClassiCube-wiiu.rpx'
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube-wiiu.elf'
          DEST_NAME: 'ClassiCube-wiiu.elf'
          
          
      - uses: ./.github/actions/notify_success
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'wiiu'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce WiiU build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
