name: Build latest (PS1)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-ps1
  cancel-in-progress: true

jobs:
  build-PS1:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/classicube/minimal-psn00b:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          apt-get update
          apt-get install -y curl

      - name: Compile PS1 build
        run: |
          export PSN00BSDK_ROOT=/usr/local/psnoob
          make ps1


      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'build/ps1/ClassiCube-ps1.elf'
          DEST_NAME: 'ClassiCube-PS1.elf'

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube-ps1.exe'
          DEST_NAME: 'ClassiCube-PS1.exe'
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube-ps1.bin'
          DEST_NAME: 'ClassiCube-PS1.bin'
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube-ps1.cue'
          DEST_NAME: 'ClassiCube-PS1.cue'
          
          
      - uses: ./.github/actions/notify_success
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'ps1'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce PS1 build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
