name: Build latest (PS3)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-ps3
  cancel-in-progress: true

jobs:
  build-PS3:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/classicube/minimal-psl1ght:latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile PS3 build
        id: compile
        run: |
          apt-get update
          apt-get install -y curl
          export PS3DEV=/usr/local/ps3dev
          export PSL1GHT=/usr/local/ps3dev
          export PATH=$PATH:$PS3DEV/bin
          export PATH=$PATH:$PS3DEV/ppu/bin
          make ps3


      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile PS3 build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'


      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube-PS3.elf'
          DEST_NAME: 'ClassiCube-PS3.elf'

      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube-PS3.self'
          DEST_NAME: 'ClassiCube-PS3.self'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube-PS3.pkg'
          DEST_NAME: 'ClassiCube-PS3.pkg'
          
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'ps3'
