name: Build latest (iOS)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
      - ios_no_arc
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-ios
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    runs-on: macOS-14
    steps:
      - uses: actions/checkout@v4
      - name: Compile iOS build
        run: | 
          export XCODE_APP=Xcode_15.0.1.app

          # Include libarclite for older iOS support (might not be needed though)
          export _arc_dir="/Applications/${XCODE_APP}/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc"
          sudo mkdir "${_arc_dir}"

          sudo curl -L -o "${_arc_dir}"/libarclite_iphoneos.a https://raw.githubusercontent.com/kamyarelyasi/Libarclite-Files/refs/heads/main/libarclite_iphoneos.a

          test "$(shasum -a 256 "${_arc_dir}"/libarclite_iphoneos.a | cut -d' ' -f1)" == "9d54588c2287cdaf3905b6eaaf857d62e390604205990d3ac7c44ccacccf6d79" || \
            (echo "Failed to verify legacy support files checksum"; exit 1)

          # Back to regular build process
          export IOS_SDK_VERSION=17.0
          make ios

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube-iPhoneOS.ipa'
          DEST_NAME: 'cc-TESTING.ipa'


      - uses: ./.github/actions/notify_success
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'ios'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce iOS build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
