name: Build latest (iOS)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-ios
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    runs-on: macOS-14
    steps:
      - uses: actions/checkout@v4
      - name: Compile iOS build
        run: |
          cd misc/ios
          sudo xcode-select -s /Applications/Xcode_15.0.1.app/Contents/Developer
          xcodebuild -sdk iphoneos -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          cd build/Release-iphoneos
          mkdir Payload
          mv ClassiCube.app Payload/ClassiCube.app
          zip -r cc.ipa Payload
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'misc/ios/build/Release-iphoneos/cc.ipa'
          DEST_NAME: 'cc.ipa'
          
          
      - uses: ./.github/actions/notify_success
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'ios'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce iOS build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
