name: Build latest (Vita)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-vita
  cancel-in-progress: true

jobs:
  build-Vita:
    runs-on: ubuntu-latest
    container:
      image: vitasdk/vitasdk:latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Vita build
        id: compile
        run: |
          make vita
          

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile Vita build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube-vita.vpk'
          DEST_NAME: 'ClassiCube-vita.vpk'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube-vita.elf'
          DEST_NAME: 'ClassiCube-vita.elf'
          
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'vita'