name: Build latest (3DS)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-3ds
  cancel-in-progress: true

jobs:
  build-3DS:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile 3DS build
        id: compile
        run: |
          make 3ds
          

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile 3DS build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube-3ds.cia'
          DEST_NAME: 'ClassiCube-3ds.cia'
                    
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube-3ds.3dsx'
          DEST_NAME: 'ClassiCube-3ds.3dsx'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube-3ds.elf'
          DEST_NAME: 'ClassiCube-3ds.elf'
          
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: '3ds'