name: Build latest (Xbox)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-xbox
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xboxdev/nxdk:git-e955705a
    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          apk add curl curl-dev

      - name: Compile Xbox build
        run: |
          eval $(/usr/src/nxdk/bin/activate -s)
          make xbox
          
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube-xbox.xbe'
          DEST_NAME: 'ClassiCube-xbox.xbe'
          
      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: 'ClassiCube-xbox.iso'
          DEST_NAME: 'ClassiCube-xbox.iso'
          
          
      - uses: ./.github/actions/notify_success
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'xbox'
          

      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce Xbox build'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
